### ISSUE TITLE
Errors with /btool, tab completion and add support for logging voxelsniper operations

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/fastasyncvoxelsniper#29]
**[REQUIRED] FastAsyncVoxelSniper Configuration Files**
https://athion.net/ISPaster/paste/view/be66988671ec45bda1daa14e78e468b1

**Required Information**
- FAVS Version Number (`/version VoxelSniper`): VoxelSniper version 1.0.4-backward
- Spigot/Paper Version Number (`/version`): git-Tuinity-"1382473" (MC: 1.16.5)
- Minecraft Version: 1.16.5

**Describe the bug**
This is a combination of bugs / features but this template is better for describing these problems. I'll just list the problems I've noticed in this issue rather than creating multiple issues.

Edits with VoxelSniper are not logged by FAWE but it would be very useful if they were, example of using `/b v`, `/btool remove` and then `/brush inspect`:
![2021-05-14_12 50 21](https://user-images.githubusercontent.com/10485646/118266993-4aae1380-b4b3-11eb-9d25-1807545536f6.png)

I'm not sure if this is a problem with other commands too but I noticed that with `/btool` there are no suggested tab completions: 
![2021-05-14_12 56 13](https://user-images.githubusercontent.com/10485646/118267321-c60fc500-b4b3-11eb-8c75-c4a8e4397a9e.png)

Running `/btool` on its own to see if the server will explain how to use the subcommands just results in an error in console:
```
[12:57:31 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'btool' in com.thevoxelbox.voxelsniper.command.Command(brush_toolkit)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2258) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2073) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2026) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1321) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1314) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1290) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at com.thevoxelbox.voxelsniper.command.executor.BrushToolkitExecutor.executeCommand(BrushToolkitExecutor.java:35) ~[?:?]
        at com.thevoxelbox.voxelsniper.command.Command.execute(Command.java:46) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
        ... 18 more
```

**To Reproduce**
Explained in the bug section

**Plugins being used on the server**
BungeeGuard, FastAsyncWorldEdit (WorldEdit), LuckPerms, PlotSquared, spark, VoxelSniper

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/voxel-sniper-flattened/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncVoxelSniper for 1.16.4](https://ci.athion.net/job/FastAsyncVoxelSniper-flattening/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Aurelien30000** [comment]
Sorry for this late answer, I'll try to fix remaining main FAVS issues. What is the command ``/btool`` supposed to do?

**Comment by SecretlyJealous** [comment]
> Sorry for this late answer, I'll try to fix remaining main FAVS issues. What is the command `/btool` supposed to do?

`/btool` on its own should explain to the player that the command requires an argument. /btool assign <arrow|powder> <toolid> for example and /btool remove [toolid]
