### ISSUE TITLE
Handling Paper-only methods gracefully

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/fastasyncvoxelsniper#47]
```
[10:02:58] [Server thread/INFO]: NotMyFault issued server command: /b b
[10:02:58] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'b b' in com.thevoxelbox.voxelsniper.command.Command(brush)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:770) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1770) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1751) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1133) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1109) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1039) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean org.bukkit.Material.isEmpty()'
	at com.thevoxelbox.voxelsniper.sniper.Sniper.getCurrentToolkit(Sniper.java:74) ~[?:?]
	at com.thevoxelbox.voxelsniper.command.executor.BrushExecutor.executeCommand(BrushExecutor.java:44) ~[?:?]
	at com.thevoxelbox.voxelsniper.command.Command.execute(Command.java:46) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spoogot.jar:3204-Spigot-18c71bf-3ad0fb1]
	... 18 more)
```
Named method is Paper only, we should handle these gracefully.

**Comment by Aurelien30000** [comment]
Gonna fix it today
